# Generated by Django 3.0.2 on 2020-10-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20201013_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='gallery_image',
        ),
    ]
